#!/usr/bin/env sh

# check-ffi-stability.sh - golden API snapshot check for the UniFFI-generated
# Kotlin binding surface.
#
# Usage: scripts/check-ffi-stability.sh [--update] [--offline]
# (run from the repository root; scripts/generate-uniffi-kotlin.sh builds
# target/release relative to the root)
#
#   (default)  Regenerate the Kotlin bindings into a temp dir, extract the
#              public FFI surface signatures, diff them against
#              scripts/binding-api.golden, exit non-zero on mismatch.
#   --update   Overwrite the golden file (intentional FFI changes only).
#   --offline  Build the Rust core from the local cargo cache only
#              (CARGO_NET_OFFLINE=true).
#
# The golden is a flat, sorted list of signatures, one per line, extracted
# from the Kotlin generated by scripts/generate-uniffi-kotlin.sh (uniffi-bindgen
# 0.32.x, package com.mindchat.core). Captured: public classes, data class
# fields and their types, enum variants, fun signatures, interface/object
# headers. Not captured: function bodies and UniFFI boilerplate (FfiConverter*,
# Uniffi*, RustBuffer, callback plumbing) - boilerplate churns on tooling
# upgrades, not on FFI changes, so it would only add noise to the diff.

set -eu

UPDATE=0
OFFLINE=0
for arg in "$@"; do
    case "$arg" in
        --update) UPDATE=1 ;;
        --offline) OFFLINE=1 ;;
        -h|--help)
            echo "usage: scripts/check-ffi-stability.sh [--update] [--offline]"
            exit 0
            ;;
        *)
            echo "check-ffi-stability.sh: unknown argument: $arg (expected --update and/or --offline)" >&2
            exit 2
            ;;
    esac
done

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
GOLDEN="$SCRIPT_DIR/binding-api.golden"
GENERATE="$SCRIPT_DIR/generate-uniffi-kotlin.sh"

# Make uniffi-bindgen visible when it lives in ~/.cargo/bin (rustup's default
# bin dir); generate-uniffi-kotlin.sh requires it on PATH.
case ":$PATH:" in
    *":$HOME/.cargo/bin:"*) ;;
    *)
        if [ -x "$HOME/.cargo/bin/uniffi-bindgen" ]; then
            PATH="$HOME/.cargo/bin:$PATH"
            export PATH
        fi
        ;;
esac

if ! command -v uniffi-bindgen >/dev/null 2>&1; then
    echo "uniffi-bindgen is required; install it with: cargo install uniffi --version 0.32.0 --features cli --locked" >&2
    exit 1
fi

TMP_DIR=$(mktemp -d "${TMPDIR:-/tmp}/mindchat-ffi.XXXXXX")
trap 'rm -rf "$TMP_DIR"' EXIT HUP INT TERM

# Regenerate the bindings into the temp dir. generate-uniffi-kotlin.sh builds
# the host lib itself; CARGO_NET_OFFLINE makes that build honour --offline
# without modifying the generator.
if [ "$OFFLINE" -eq 1 ]; then
    CARGO_NET_OFFLINE=true
    export CARGO_NET_OFFLINE
fi
sh "$GENERATE" "$TMP_DIR"

KOTLIN="$TMP_DIR/com/mindchat/core/mindchat_core.kt"
if [ ! -f "$KOTLIN" ]; then
    echo "check-ffi-stability.sh: generated bindings not found: $KOTLIN" >&2
    exit 1
fi

# Signature extractor: state machine over the generated Kotlin. The surface is
# the Ffi* records/enums/events, the MindChatCoreHandle contract and
# MindChatBindingException; see the header comment of this script.
cat > "$TMP_DIR/extract.awk" <<'AWK'
function emit(line,    s) {
    s = line
    gsub(/`/, "", s)
    gsub(/^[ \t]+|[ \t]+$/, "", s)
    if (s != "") print s
}

function is_surface(line) {
    if (line ~ /^[ \t]*(public[ \t]+)?(open[ \t]+)?(sealed[ \t]+)?(data[ \t]+)?(enum[ \t]+)?class[ \t]+Ffi[A-Za-z0-9_]*( |\(|\{|:)/) {
        if (line !~ /FfiConverter/) return 1
    }
    if (line ~ /^[ \t]*(public[ \t]+)?(open[ \t]+)?(sealed[ \t]+)?(data[ \t]+)?class[ \t]+MindChat(CoreHandle|CoreHandleInterface|BindingException)/) return 1
    if (line ~ /^[ \t]*(public[ \t]+)?interface[ \t]+MindChatCoreHandleInterface/) return 1
    if (line ~ /^[ \t]*(public[ \t]+)?object[ \t]+(Ffi[A-Za-z0-9_]*|MindChat[A-Za-z0-9_]*)[ \t]*([:({]|$)/) {
        if (line !~ /FfiConverter|Uniffi/) return 1
    }
    return 0
}

BEGIN {
    in_iface = 0
    in_enum = 0
    in_record = 0
    in_event = 0
    in_event_class = 0
    in_error = 0
    in_error_class = 0
}

{
    line = $0

    if (in_iface) {
        if (line ~ /^[ \t]*fun /) { emit(line) }
        else if (line ~ /^}[ \t]*$/) { in_iface = 0 }
        next
    }

    if (in_enum) {
        if (line ~ /^[ \t]*[A-Z][A-Z0-9_]*[ \t]*[,;]?[ \t]*$/) {
            v = line
            sub(/[ \t]*[,;][ \t]*$/, "", v)
            emit(v)
        } else if (line ~ /^[ \t]*companion[ \t]|^}[ \t]*$/) {
            in_enum = 0
        }
        next
    }

    if (in_record) {
        if (line ~ /^\)/) { in_record = 0 }
        else if (line ~ /^[ \t]*val[ \t]/ && line !~ /^[ \t]*override/) { emit(line) }
        next
    }

    if (in_event) {
        if (in_event_class) {
            if (line ~ /^[ \t]*val[ \t]/ && line !~ /^[ \t]*override/) {
                v = line
                sub(/\)[ \t]*:[ \t]*FfiCoreEvent\(\)[ \t]*$/, "", v)
                emit(v)
            } else if (line ~ /^[ \t]*\}[ \t]*$/) {
                in_event_class = 0
            }
            next
        }
        if (line ~ /^[ \t]*data[ \t]+class[ \t]+[A-Za-z0-9_]+\(/) {
            emit(line)
            in_event_class = 1
        } else if (line ~ /^}[ \t]*$/) {
            in_event = 0
        }
        next
    }

    if (in_error) {
        if (in_error_class) {
            if (line ~ /^[ \t]*val[ \t]/ && line !~ /^[ \t]*override/) {
                emit(line)
            } else if (line ~ /^[ \t]*\)[ \t]*:[ \t]*MindChatBindingException\(\)[ \t]*\{/) {
                in_error_class = 0
            }
            next
        }
        if (line ~ /^[ \t]*class[ \t]+[A-Za-z0-9_]+\(/) {
            emit(line)
            in_error_class = 1
        } else if (line ~ /^}[ \t]*$/) {
            in_error = 0
        }
        next
    }

    if (is_surface(line)) {
        if (line ~ /^[ \t]*public[ \t]+interface/) { in_iface = 1 }
        else if (line ~ /^[ \t]*enum[ \t]+class/) { in_enum = 1 }
        else if (line ~ /^[ \t]*sealed[ \t]+class[ \t]+FfiCoreEvent/) { in_event = 1 }
        else if (line ~ /^[ \t]*sealed[ \t]+class[ \t]+MindChatBindingException/) { in_error = 1 }
        else if (line ~ /^[ \t]*(public[ \t]+)?data[ \t]+class/) { in_record = 1 }
        h = line
        sub(/[ \t]+\($/, "(", h)
        emit(h)
        next
    }
}
AWK

EXTRACTED="$TMP_DIR/extracted.txt"
awk -f "$TMP_DIR/extract.awk" "$KOTLIN" | LC_ALL=C sort > "$EXTRACTED"
SIG_COUNT=$(wc -l < "$EXTRACTED" | tr -d ' ')

GOLDEN_HEADER='# Golden API snapshot of the MindChat UniFFI Kotlin binding surface.
# Generated by scripts/check-ffi-stability.sh from the output of
# scripts/generate-uniffi-kotlin.sh (uniffi-bindgen 0.32.x, package com.mindchat.core).
# One signature per line, sorted. Do not edit by hand.
# After an intentional FFI change, regenerate with:
#   scripts/check-ffi-stability.sh --update
# (add --offline when the local cargo cache must be used instead of the network)'

if [ "$UPDATE" -eq 1 ]; then
    {
        printf '%s\n' "$GOLDEN_HEADER"
        cat "$EXTRACTED"
    } > "$GOLDEN"
    echo "check-ffi-stability.sh: updated $GOLDEN ($SIG_COUNT signatures)"
    exit 0
fi

if [ ! -f "$GOLDEN" ]; then
    echo "check-ffi-stability.sh: golden file missing: $GOLDEN (run with --update to create it)" >&2
    exit 1
fi

# Compare signature payloads; comment lines in the golden are just the header.
GOLDEN_SIGS="$TMP_DIR/golden.txt"
grep -v '^#' "$GOLDEN" > "$GOLDEN_SIGS"

if diff -u "$GOLDEN_SIGS" "$EXTRACTED" > "$TMP_DIR/diff.txt"; then
    echo "check-ffi-stability.sh: PASS: $SIG_COUNT signatures match $GOLDEN"
    exit 0
fi

echo "check-ffi-stability.sh: FAIL: FFI surface differs from the golden snapshot." >&2
echo "If this is an intentional FFI change, run: scripts/check-ffi-stability.sh --update" >&2
echo "diff (golden vs regenerated):" >&2
cat "$TMP_DIR/diff.txt" >&2
exit 1
