#!/usr/bin/env bash
set -euo pipefail

# MindChat ops: provision a single-user XMPP lab server on a FRESH
# Ubuntu 22.04+ / Debian 12 box. Gives the owner the controlled test server
# the project currently lacks (MAM history, MUC, HTTP file upload, and a
# base for later UnifiedPush testing).
#
# Assumptions and limits (honest):
#   - The box is FRESH; this is not idempotent across re-runs.
#   - You are root or sudo-capable (script self-elevates nothing).
#   - A DNS A/AAAA record for $DOMAIN already points at this machine.
#     TLS will fail without it; there is no way around that.
#   - Single-admin, personal-lab posture. NOT hardened for multi-user or
#     public registration (registration is deliberately left off).
#   - Provider-agnostic: plain apt + systemd only.
#
# Usage:
#   sudo ./prosody-vps-setup.sh [--letsencrypt <domain>]
#     --letsencrypt <domain>: obtain a real certificate via certbot
#     (standalone challenge on port 80) and import it for Prosody.
#     Without the flag, a self-signed certificate is generated instead
#     and clients must be told to trust/accept it.

if [[ $EUID -ne 0 ]]; then
    echo "run as root: sudo $0 $*" >&2
    exit 1
fi

LETSENCRYPT_DOMAIN=""
if [[ "${1:-}" == "--letsencrypt" ]]; then
    LETSENCRYPT_DOMAIN="${2:-}"
    [[ -n "$LETSENCRYPT_DOMAIN" ]] || { echo "usage: $0 --letsencrypt <domain>" >&2; exit 64; }
fi

read -r -p "XMPP domain (e.g. chat.example.com — must already resolve here): " XMPP_DOMAIN
[[ "$XMPP_DOMAIN" =~ ^[a-z0-9.-]+\.[a-z]{2,}$ ]] || { echo "not a domain name: $XMPP_DOMAIN" >&2; exit 64; }

read -r -p "Admin JID local part [admin]: " ADMIN_LOCAL
ADMIN_LOCAL=${ADMIN_LOCAL:-admin}

while true; do
    read -rs -p "Password for ${ADMIN_LOCAL}@${XMPP_DOMAIN}: " ADMIN_PASS
    echo
    [[ -n "$ADMIN_PASS" ]] && break
done

read -r -p "Enable MUC component? [Y/n]: " WANT_MUC
ENABLE_MUC=$(echo "${WANT_MUC:-Y}" | tr '[:upper:]' '[:lower:]')
MUC_HOST="conference.${XMPP_DOMAIN}"
if [[ "$ENABLE_MUC" != n ]]; then
    read -r -p "MUC host [${MUC_HOST}]: " MUC_INPUT
    MUC_HOST=${MUC_INPUT:-$MUC_HOST}
fi

read -r -p "Enable HTTP file upload? [Y/n]: " WANT_UPLOAD
ENABLE_UPLOAD=$(echo "${WANT_UPLOAD:-Y}" | tr '[:upper:]' '[:lower:]')
UPLOAD_HOST="upload.${XMPP_DOMAIN}"
if [[ "$ENABLE_UPLOAD" != n ]]; then
    read -r -p "Upload host [${UPLOAD_HOST}]: " UPLOAD_INPUT
    UPLOAD_HOST=${UPLOAD_INPUT:-$UPLOAD_HOST}
fi

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq prosody prosody-modules

CONF="/etc/prosody/conf.avail/${XMPP_DOMAIN}.cfg.lua"

MODULES="'roster'; 'saslauth'; 'tls'; 'dialback'; 'disco'; 'carbons'; 'pep'; 'private'; 'blocklist'; 'vcard4'; 'vcard_legacy'; 'version'; 'uptime'; 'time'; 'ping'; 'register'; -- keep register OFF for public use
         'mam'; 'archive_mam'"

cat > "$CONF" <<EOF
-- Generated by scripts/prosody-vps-setup.sh for MindChat's private lab.
VirtualHost "${XMPP_DOMAIN}"
	admins = { "${ADMIN_LOCAL}@${XMPP_DOMAIN}" }

	-- Registration intentionally disabled: personal lab, not a public host.
	allow_registration = false

	modules_enabled = {
${MODULES}
	}
EOF

if [[ "$ENABLE_MUC" != n ]]; then
    cat >> "$CONF" <<EOF

Component "${MUC_HOST}" "muc"
	modules_enabled = { 'muc_mam'; 'vcard_muc' }
	restrict_room_creation = false
EOF
fi

if [[ "$ENABLE_UPLOAD" != n ]]; then
    cat >> "$CONF" <<EOF

Component "${UPLOAD_HOST}" "http_upload"
	-- 64 MiB per file, 512 MiB total; tighten if the disk is small.
	http_upload_file_size_limit = 64 * 1024 * 1024
	http_upload_quota = 512 * 1024 * 1024
EOF
fi

ln -sf "../conf.avail/${XMPP_DOMAIN}.cfg.lua" "/etc/prosody/conf.d/${XMPP_DOMAIN}.cfg.lua"
# Debian ships an example.com vhost that would otherwise fight ours.
rm -f /etc/prosody/conf.d/example.com.cfg.lua /etc/prosody/conf.avail/example.com.cfg.lua

if [[ -n "$LETSENCRYPT_DOMAIN" ]]; then
    apt-get install -y -qq certbot
    certbot certonly --standalone -d "$LETSENCRYPT_DOMAIN" --non-interactive --agree-tos \
        --register-unsafely-without-email || {
        echo "certbot failed: is port 80 free and DNS pointed here?" >&2
        exit 1
    }
    prosodyctl cert import /etc/letsencrypt/live
else
    prosodyctl cert generate "$XMPP_DOMAIN"
    echo "NOTE: self-signed certificate generated; clients must accept it manually."
fi

prosodyctl register "$ADMIN_LOCAL" "$XMPP_DOMAIN" "$ADMIN_PASS"
prosodyctl check
systemctl enable --now prosody
systemctl restart prosody

cat <<EOF

=============================================================
 Done. Summary for ${XMPP_DOMAIN}
-------------------------------------------------------------
 Account : ${ADMIN_LOCAL}@${XMPP_DOMAIN}

 Open these ports in your firewall/security group:
   5222/tcp  client-to-server (required)
   5269/tcp  server-to-server (only if you want federation)
   5281/tcp  HTTPS file upload + BOSH/WS (if upload enabled)
   80/tcp    ACME renewals (letsencrypt path only)
   443/tcp   optional direct-TLS client port if you add one

 Certificates:
$( [[ -n "$LETSENCRYPT_DOMAIN" ]] && echo "   Let's Encrypt via certbot; auto-imported. Add a renewal hook:" && echo "   systemctl edit --full certbot.timer  ->  ExecStartAdd=prosodyctl cert import /etc/letsencrypt/live" || echo "   Self-signed; fine for a private lab, replace when convenient.")

 Next steps:
   1. Register a SECOND account (prosodyctl register test ...) so you can
      test 1:1 flows between two users.
   2. Point MindChat at this server (host ${XMPP_DOMAIN}, direct TLS).
   3. Later: enable mod_unified_push (prosody-modules >= recent) to get a
      real push target for the app's UnifiedPush work.
=============================================================
EOF
